[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# [[plugins]]
# repo = "davidhalter/jedi-vim"
# on_ft = ['python']

[[plugins]]
repo = "andviro/flake8-vim"
on_ft = ['python']

[[plugins]]
repo = "hynek/vim-python-pep8-indent"
on_ft = ['python']

# markdown
[[plugins]]
repo = "plasticboy/vim-markdown"
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = "kannokanno/previm"
on_ft = ['markdown', 'mkd', 'md']

# プレビューをブラウザで開いてくれる
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

[[plugins]]
repo = "jmcantrell/vim-virtualenv"
on_ft = ['python']

# Scala
[[plugins]]
repo = "derekwyatt/vim-scala"
on_ft = ['scala']

# Golang
[[plugins]]
repo = "fatih/vim-go"
on_ft = ['go']

# LaTeX
[[plugins]]
repo = "vim-latex/vim-latex"
on_ft = ['tex']

[[plugins]]
repo="rust-lang/rust.vim"
on_ft = ['rs']

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
autocmd! BufEnter,BufWritePost * Neomake
let g:neomake_python_enabled_makers = ['python', 'flake8', 'mypy']
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = "!has('nvim')"
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" for Python
let g:syntastic_python_checkers = ['python', 'flake8', 'mypy']
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1
